name: opinionated_pagination
description: An ellipsis pagination solution for Flutter. Designed with Riverpod, but should work with any state management solution.
version: 1.0.0+1
homepage: 'https://github.com/noskap/opinionated_pagination'

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: